---
  version: 2.1
  orbs:
    ruby: circleci/ruby@0.2.1

  jobs:
    test:
      working_directory: ~/vets-api
      docker:
        - image: circleci/ruby:2.6.5-stretch
          environment:
            BUNDLE_JOBS: 2
            BUNDLE_RETRY: 3
            LANG: en_US.UTF-8
            PGHOST: localhost
            PGUSER: vets-api
            RAILS_ENV: test
            "Settings.saml.cert_path": "spec/support/certificates/ruby-saml.crt"
            "Settings.saml.key_path": "spec/support/certificates/ruby-saml.key"
            "Settings.binaries.clamdscan": "clamscan"
        - image: circleci/postgres:11.5-postgis-ram # 11.5 engine on AWS RDS
          environment:
            POSTGRES_USER: vets-api
            POSTGRES_DB: vets-api_test
            POSTGRES_PASSWORD: ""
        - image: circleci/redis:3.2-alpine # 3.2.4 engine on AWS Elasticache
      steps:
        - checkout
        - ruby/load-cache
        - ruby/install-deps
        - ruby/save-cache
        - run:
            command: sudo apt install pdftk poppler-utils
        - run:
            name: setup database
            command: bundle exec rake db:create db:schema:load
        - run:
            name: Audit bundled gems for CVE issues
            command: bundle exec bundle-audit check --update
        - run:
            name: Static security analysis using Brakeman
            command: bundle exec brakeman --exit-on-warn --run-all-checks --confidence-level=2 --format=plain
        - run:
            name: Lint code with Rubocop
            command: bundle exec rubocop -r rubocop-thread_safety
        - run:
            name: Run all RSpec specs
            command: bundle exec rspec

  workflows:
    workflow:
      jobs:
        - test
