---
  version: 2.1
  orbs:
    ruby: circleci/ruby@0.2.1


    environment:


  jobs:
    test:
      docker:
        - image: circleci/ruby:2.6.5-stretch
          environment:
            BUNDLE_JOBS: 2
            BUNDLE_RETRY: 3
            BUNDLE_PATH: vendor/bundle
            DATABASE_URL: "postgis://root@localhost/vets-api-test"
            PGHOST: 127.0.0.1
            PGUSER: vsp
            PGPASSWORD: sekrit
        - image: circleci/postgres:11.5-postgis-ram # 11.5 engine on AWS RDS
          environment:
            POSTGRES_USER: vsp
            POSTGRES_PASSWORD: sekrit
            POSTGRES_DB: vets-api-test
        - image: circleci/redis:3.2-alpine # 3.2.4 engine on AWS Elasticache
      steps:
        - checkout
        - ruby/load-cache
        - ruby/install-deps
        - run:
            name: setup database
            command: bundle exec rake db:create db:migrate
            environment:
              RAILS_ENV: test
        - run:
            name: run tests
            command: bundle exec rake test
            environment:
              RAILS_ENV: test
        - ruby/save-cache

  workflows:
    workflow:
      jobs:
        - test